#!/bin/bash

docker pull registry.transplace.com/tplace/openshift-client:latest
docker container run --user root -e OC_HOST=${OC_HHOST} -e TOKEN=${TOKEN} -e OC_IMAGE=${OC_IMAGE} -e PROJECT_NAME=${PROJECT_NAME} -e REMOTE_IMAGE=${REMOTE_IMAGE} registry.transplace.com/tplace/openshift-client:latest bash /tag-to-image-stream.sh
